# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    -   repo: local
        hooks:
            #Use dotnet format already installed on your machine
            -   id: dotnet-format
                name: dotnet-format
                language: system
                entry: dotnet format --include
                types_or: ["c#", "vb"]