// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable RS0016
#pragma warning disable CS8981
#pragma warning disable RS0041

namespace ConferencePlanner.Service.Migrations
{
    using System.Diagnostics.CodeAnalysis;

    /// <inheritdoc />
    [SuppressMessage("ApiDesign", "RS0016:Add public types and members to the declared API")]
    public partial class initital : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
